### ISSUE TITLE
Update CheersUser data model to have DrinkEvents

### ISSUE THREAD

**Issue by MicahRamirez** [MicahRamirez/cs378-iOS#4]
Any user should be able to take part in N DrinkEvents. A DrinkEvent can have many users attending it.

**Comment by AndyTTang** [comment]
Created an attribute for Drink Events to have an array that contains invited users.

My concern is that when including the invitees in the DrinkEvent, it expects the user along with their friendslist since each user has a friendslist (extraneous unnecessary info?)
